import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { Navbar } from "./_shared/containers/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(
        inter.className,
        'flex items-center justify-center flex-col min-h-screen'
      )}>
        <Navbar />
        <div
          className='flex items-stretch flex-1 w-full'
        >
          {children}
        </div>
      </body>
    </html>
  );
}
